export default function page() {
  return (
    <section className="my-12">
      <div className="container mx-auto px-4 text-left">
        <h2 className="font-custom mb-8 text-center text-3xl font-semibold text-gray-800 dark:text-gray-200">
          Privacy Policy for Konjo Habesha Fashion
        </h2>
        <div className="text-md mb-12 leading-relaxed text-gray-600 dark:text-gray-300">
          <p className="mb-4">Last updated: February 19, 2024</p>
          <p className="mb-4">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="mb-4">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Privacy Policy
            Generator.
          </p>
        </div>

        {/* Interpretation and Definitions */}
        <div>
          <h2 className="font-custom mb-8 text-center text-3xl font-semibold text-gray-800 dark:text-gray-200">
            Interpretation and Definitions
          </h2>
          <p className="text-md mb-4 leading-relaxed text-gray-600 dark:text-gray-300">
            The following definitions are used in this Privacy Policy:
          </p>
          <div className="list-inside list-disc text-gray-600 dark:text-gray-300">
            <ul className="flex flex-col gap-4">
              <li>
                <strong>Account:</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate:</strong> means an entity that controls, is
                controlled by or is under common control with a party, where
                &quot;control&quot; means ownership of 50% or more of the
                shares, equity interest or other securities entitled to vote for
                election of directors or other managing authority.
              </li>
              <li>
                <strong>Company:</strong> (referred to as either &quot;the
                Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
                in this Agreement) refers to Konjo Habesha Fashion.
              </li>
              <li>
                <strong>Cookies:</strong> are small files that are placed on
                Your computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website
                among its many uses.
              </li>
              <li>
                <strong>Country:</strong> refers to Ethiopia
              </li>
              <li>
                <strong>Device:</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Data:</strong> is any information that relates
                to an identified or identifiable individual.
              </li>
              <li>
                <strong>Service:</strong> refers to the Website.
              </li>
              <li>
                <strong>Service Provider:</strong> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is
                used.
              </li>
              <li>
                <strong>Third-party Social Media Service:</strong> refers to any
                website or any social network website through which a User can
                log in or create an account to use the Service.
              </li>
              <li>
                <strong>Usage Data:</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>

              <li>
                <strong>You:</strong> means the individual accessing or using
                the Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
              <li>
                <strong>Website:</strong> refers to Konjo Habesha Fashion,
                accessible from
                <a
                  href="https://konjo-habesha-fashion.vercel.app/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="ml-2 text-blue-500 hover:underline"
                >
                  https://konjo-habesha-fashion.vercel.app/
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div>
          <h2 className="font-custom my-8 text-center text-3xl font-semibold text-gray-800 dark:text-gray-200">
            Types of Data Collected
          </h2>
          <p className="text-md mb-4 text-xl font-semibold leading-relaxed text-gray-600 dark:text-gray-300">
            Types of Data Collected
          </p>
          <p className="text-md mb-4 text-lg font-semibold leading-relaxed text-gray-600 dark:text-gray-300">
            Personal Data
          </p>

          <p className=" mb-4">
            {" "}
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className=" list-inside list-disc">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <p className="text-md my-4 text-lg font-semibold leading-relaxed text-gray-600 dark:text-gray-300 ">
            Usage Data
          </p>

          <p className=" mb-4">
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as Your Device&apos;s Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data. <br />
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data. <br />
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>

          <p className="text-md my-4 text-lg font-semibold leading-relaxed text-gray-600 dark:text-gray-300 ">
            Information from Third-Party Social Media Services
          </p>
          <p className=" mb-4">
            The Company allows You to create an account and log in to use the
            Service through the following Third-party Social Media Services:
          </p>
          <ul className=" flex list-inside list-disc flex-col gap-2">
            <li>Google</li>
            <li>Facebook</li>
          </ul>
          <p className=" my-4">
            If You decide to register through or otherwise grant us access to a
            Third-Party Social Media Service, We may collect Personal data that
            is already associated with Your Third-Party Social Media
            Service&apos;s account, such as Your name, Your email address, Your
            activities or Your contact list associated with that account.
          </p>

          <p className="my-4">
            You may also have the option of sharing additional information with
            the Company through Your Third-Party Social Media Service&apos;s
            account. If You choose to provide such information and Personal
            Data, during registration or otherwise, You are giving the Company
            permission to use, share, and store it in a manner consistent with
            this Privacy Policy.
          </p>
        </div>
        <div className="container mx-auto px-4 text-left">
          <h2 className="font-custom mb-8 text-center text-3xl font-semibold text-gray-800 dark:text-gray-200">
            Tracking Technologies and Cookies
          </h2>
          <div className="text-md mb-12 leading-relaxed text-gray-600 dark:text-gray-300">
            <p>
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information. Tracking
              technologies used are beacons, tags, and scripts to collect and
              track information and to improve and analyze Our Service. The
              technologies We use may include:
            </p>
            <ul className=" flex flex-col gap-4">
              <li>
                <strong>Cookies or Browser Cookies:</strong> A cookie is a small
                file placed on Your Device. You can instruct Your browser to
                refuse all Cookies or to indicate when a Cookie is being sent.
                However, if You do not accept Cookies, You may not be able to
                use some parts of our Service. Unless you have adjusted Your
                browser setting so that it will refuse Cookies, our Service may
                use Cookies.
              </li>
              <li>
                <strong>Web Beacons:</strong> Certain sections of our Service
                and our emails may contain small electronic files known as web
                beacons (also referred to as clear gifs, pixel tags, and
                single-pixel gifs) that permit the Company, for example, to
                count users who have visited those pages or opened an email and
                for other related website statistics (for example, recording the
                popularity of a certain section and verifying system and server
                integrity).
              </li>
            </ul>
            <p>
              Cookies can be &quote;Persistent&quote; or &quote;Session&quote;
              Cookies. Persistent Cookies remain on Your personal computer or
              mobile device when You go offline, while Session Cookies are
              deleted as soon as You close Your web browser. You can learn more
              about cookies on TermsFeed website article.
            </p>
          </div>
          <div className="text-md mb-12 leading-relaxed text-gray-600 dark:text-gray-300">
            <p>
              <strong>
                We use both Session and Persistent Cookies for the purposes set
                out below:
              </strong>
            </p>
            <ul>
              <li>
                <strong>Necessary / Essential Cookies</strong>
                <ul>
                  <li>
                    <strong>Type:</strong> Session Cookies
                  </li>
                  <li>
                    <strong>Administered by:</strong> Us
                  </li>
                  <li>
                    <strong>Purpose:</strong> These Cookies are essential to
                    provide You with services available through the Website and
                    to enable You to use some of its features. They help to
                    authenticate users and prevent fraudulent use of user
                    accounts. Without these Cookies, the services that You have
                    asked for cannot be provided, and We only use these Cookies
                    to provide You with those services.
                  </li>
                </ul>
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong>
                <ul>
                  <li>
                    <strong>Type:</strong> Persistent Cookies
                  </li>
                  <li>
                    <strong>Administered by:</strong> Us
                  </li>
                  <li>
                    <strong>Purpose:</strong> These Cookies identify if users
                    have accepted the use of cookies on the Website.
                  </li>
                </ul>
              </li>
              <li>
                <strong>Functionality Cookies</strong>
                <ul>
                  <li>
                    <strong>Type:</strong> Persistent Cookies
                  </li>
                  <li>
                    <strong>Administered by:</strong> Us
                  </li>
                  <li>
                    <strong>Purpose:</strong> These Cookies allow us to remember
                    choices You make when You use the Website, such as
                    remembering your login details or language preference. The
                    purpose of these Cookies is to provide You with a more
                    personal experience and to avoid You having to re-enter your
                    preferences every time You use the Website.
                  </li>
                </ul>
              </li>
            </ul>
            <p>
              For more information about the cookies we use and your choices
              regarding cookies, please visit our Cookies Policy or the Cookies
              section of our Privacy Policy.
            </p>
          </div>
          <div className="text-md mb-12 leading-relaxed text-gray-600 dark:text-gray-300">
            <h2 className=" mb-4 text-lg font-semibold">
              Use of Your Personal Data
            </h2>
            <p>The Company may use Personal Data for the following purposes:</p>

            <ul className=" flex list-inside list-disc flex-col gap-4">
              <li>
                To provide and maintain our Service, including to monitor the
                usage of our Service.
              </li>
              <li>
                To manage Your Account: to manage Your registration as a user of
                the Service. The Personal Data You provide can give You access
                to different functionalities of the Service that are available
                to You as a registered user.
              </li>
              <li>
                For the performance of a contract: the development, compliance
                and undertaking of the purchase contract for the products, items
                or services You have purchased or of any other contract with Us
                through the Service.
              </li>
              <li>
                To contact You: To contact You by email, telephone calls, SMS,
                or other equivalent forms of electronic communication, such as a
                mobile application&apos;s push notifications regarding updates
                or informative communications related to the functionalities,
                products or contracted services, including the security updates,
                when necessary or reasonable for their implementation.
              </li>
              <li>
                To provide You with news, special offers and general information
                about other goods, services and events which we offer that are
                similar to those that you have already purchased or enquired
                about unless You have opted not to receive such information.
              </li>
              <li>
                To manage Your requests: To attend and manage Your requests to
                Us.
              </li>
              <li>
                For business transfers: We may use Your information to evaluate
                or conduct a merger, divestiture, restructuring, reorganization,
                dissolution, or other sale or transfer of some or all of Our
                assets, whether as a going concern or as part of bankruptcy,
                liquidation, or similar proceeding, in which Personal Data held
                by Us about our Service users is among the assets transferred.
              </li>
              <li>
                For other purposes: We may use Your information for other
                purposes, such as data analysis, identifying usage trends,
                determining the effectiveness of our promotional campaigns and
                to evaluate and improve our Service, products, services,
                marketing and your experience.
              </li>
            </ul>
            <p>
              We may share Your personal information in the following
              situations:
            </p>

            <ul className=" flex list-inside list-disc flex-col gap-4">
              <li>
                With Service Providers: We may share Your personal information
                with Service Providers to monitor and analyze the use of our
                Service, to contact You.
              </li>
              <li>
                For business transfers: We may share or transfer Your personal
                information in connection with, or during negotiations of, any
                merger, sale of Company assets, financing, or acquisition of all
                or a portion of Our business to another company.
              </li>
              <li>
                With Affiliates: We may share Your information with Our
                affiliates, in which case we will require those affiliates to
                honor this Privacy Policy. Affiliates include Our parent company
                and any other subsidiaries, joint venture partners or other
                companies that We control or that are under common control with
                Us.
              </li>
              <li>
                With business partners: We may share Your information with Our
                business partners to offer You certain products, services or
                promotions.
              </li>
              <li>
                With other users: when You share personal information or
                otherwise interact in the public areas with other users, such
                information may be viewed by all users and may be publicly
                distributed outside. If You interact with other users or
                register through a Third-Party Social Media Service, Your
                contacts on the Third-Party Social Media Service may see Your
                name, profile, pictures and description of Your activity.
                Similarly, other users will be able to view descriptions of Your
                activity, communicate with You and view Your profile.
              </li>
              <li>
                With Your consent: We may disclose Your personal information for
                any other purpose with Your consent.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}
